feat: bid auction [WIP]
deezy-inc/nosft-core pull request #44
Opened 2023-08-04 14:30 UTC by topether21

2023-08-08 13:58 UTC, habibitcoin requested changes
Pretty much good to go, but would want to understand the fee behavior a bit better. As mentioned on the other PR, we seem to be underestimating for some reason.

The issue is going to either be:
1. Some problem with estimating size in src/app/crypto.ts:29, but this looks to be correct
2. Some problem with the feeRate on src/app/crypto.ts:30. It looks like this can end up as either the value selected by the bidder, a default rate, or a recommended rate. Maybe we're accidentally not invoking the value selected by the bidder? Is that intentional perhaps?

2023-08-10 03:11 UTC, topether21 commented
@habibitcoin it is fixed, take a look at 

<img width="596" alt="image" src="https://github.com/deezy-inc/nosft-core/assets/126987350/103da57b-1576-4740-85f4-06826df804fc">

2023-08-10 03:27 UTC, topether21 commented
I added a console.log and before merge I can delete it.

<img width="759" alt="image" src="https://github.com/deezy-inc/nosft-core/assets/126987350/4045d7cf-cbe9-4132-a9b8-1f7b1e07e06d">

2023-08-10 18:00 UTC, habibitcoin approved these changes
Looks good! lets just remove the log statements prior ot merge

2023-08-10 18:00 UTC, habibitcoin commented on src/app/psbt.ts
> +                console.log('[Broadcasting tx]', hex);
yeah lets remove, but good job finding the smoking gun!

2023-08-14 17:25 UTC, andredevjs approved these changes

2023-08-14 17:25 UTC, merged